{{ if eq .chezmoi.os "darwin" -}}
[".hammerspoon/Spoons/Emojis.spoon"]
  type = "archive"
  url = "https://github.com/Hammerspoon/Spoons/raw/master/Spoons/Emojis.spoon.zip"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".hammerspoon/Spoons/ReloadConfiguration.spoon"]
  type = "archive"
  url = "https://github.com/Hammerspoon/Spoons/raw/master/Spoons/ReloadConfiguration.spoon.zip"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
{{ end -}}


################################################################################
# tmux
################################################################################

[".config/tmux/plugins/tpm"]
  type = "archive"
  url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"


################################################################################
# zsh
################################################################################

{{ if (ne .chezmoi.os "darwin") -}}
[".config/zsh/completion/_docker-compose"]
  type = "file"
  url = "https://raw.githubusercontent.com/docker/compose/master/contrib/completion/zsh/_docker-compose"
  refreshPeriod = "168h"

[".config/zsh/completion/_docker"]
  type = "file"
  url = "https://raw.githubusercontent.com/docker/cli/master/contrib/completion/zsh/_docker"
  refreshPeriod = "168h"
{{ end -}}

[".config/zsh/ohmyzsh-clipboard.zsh"]
  type = "file"
  url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/lib/clipboard.zsh"
  refreshPeriod = "168h"

[".config/zsh/ohmyzsh-completion.zsh"]
  type = "file"
  url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/lib/completion.zsh"
  refreshPeriod = "168h"

[".config/zsh/ohmyzsh-key-bindings.zsh"]
  type = "file"
  url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/lib/key-bindings.zsh"
  refreshPeriod = "168h"

[".config/zsh/zsh-syntax-highlighting"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
