[colors.bright]
black = "#666666"
blue = "#387CD3"
cyan = "#3D97E2"
green = "#77B869"
magenta = "#957BBE"
red = "#E05A4F"
white = "#BABABA"
yellow = "#EFD64B"

[colors.normal]
black = "#000000"
blue = "#1C98E8"
cyan = "#1C98E8"
green = "#68C256"
magenta = "#8E69C9"
red = "#E8341C"
white = "#BABABA"
yellow = "#F2D42C"

[colors.primary]
background = "#222324"
foreground = "#BABABA"

[shell]
args = ["-l", "-c", "/opt/homebrew/bin/tmux new -A -s default"]
program = "/opt/homebrew/bin/zsh"

[window]
decorations_theme_variant = "Dark"

[font]
# normal      = { family = "MesloLGM Nerd Font", style = "Regular" }
normal      = { family = "MonaspiceNe Nerd Font", style = "Regular" }
bold        = { family = "MonaspiceNe Nerd Font", style = "Bold" }
italic      = { family = "MonaspiceNe Nerd Font", style = "Italic" }
bold_italic = { family = "MonaspiceNe Nerd Font", style = "Bold Italic" }
size = 15.0

[colors]
line_indicator = { foreground = "#ebebf5", background = "#1e1e28" }
footer_bar     = { foreground = "#ebebf5", background = "#44445a" }
selection      = { foreground = "#1e1e28", background = "#b8ccff" }
